export type ExpertType = '일반' | '전문가' | '고급전문가' | '특수전문가';

export type ServiceChannel = '대면' | '전화(화상)' | '채팅' | '파일';
export type ServiceTaskType = '단순 편집' | '문서 작성' | '설문' | '출제' | '채점';

export type TranslatorLevelCriteria = {
  careerYears: string; // 업무 경력
  education: string; // 학벌
  field: string; // 분야
  overseasExperience: string; // 해외근무여부
  domainExperience: string; // 해당분야 경력
};

export type AdminTranslator = {
  id: number;
  name: string;
  level: 'A' | 'B' | 'C' | 'D' | 'E';
  priority: number;
  time: string;
  serviceType: string;
  workUnit: string;
  difficulty: '상' | '중' | '하';
  area: string;
  subArea: string;
  serviceChannels: ServiceChannel[];
  serviceTasks: ServiceTaskType[];
  expertType: ExpertType;
  levelCriteria: TranslatorLevelCriteria;
  rating: number;
  completedCount: number;
  profileImageUrl: string;
};

export const adminTranslators: AdminTranslator[] = [
  {
    id: 1,
    name: '김번역',
    level: 'A',
    priority: 1,
    time: '평일 오전',
    serviceType: '문서 번역',
    workUnit: '글자수',
    difficulty: '상',
    area: '법률',
    subArea: '민사법',
    serviceChannels: ['대면', '전화(화상)', '파일'],
    serviceTasks: ['문서 작성', '단순 편집'],
    expertType: '고급전문가',
    levelCriteria: {
      careerYears: '10년',
      education: '국내 로스쿨 석사',
      field: '민사/상사 소송',
      overseasExperience: '미국 로펌 파견 2년',
      domainExperience: '민사 소송 서류 번역 300건+',
    },
    rating: 4.9,
    completedCount: 320,
    profileImageUrl: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 2,
    name: '이나라',
    level: 'A',
    priority: 2,
    time: '평일 오후',
    serviceType: '계약서 번역',
    workUnit: '장당',
    difficulty: '상',
    area: '법률',
    subArea: '형사법',
    serviceChannels: ['전화(화상)', '파일'],
    serviceTasks: ['문서 작성'],
    expertType: '전문가',
    levelCriteria: {
      careerYears: '8년',
      education: 'OO대 법학과',
      field: '형사 사건',
      overseasExperience: '유학 1년 (영국)',
      domainExperience: '형사 조서/판결문 번역 200건+',
    },
    rating: 4.8,
    completedCount: 210,
    profileImageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 3,
    name: '박글로벌',
    level: 'B',
    priority: 3,
    time: '주말',
    serviceType: 'IR 자료 번역',
    workUnit: '페이지',
    difficulty: '중',
    area: '경영',
    subArea: '영업',
    serviceChannels: ['파일'],
    serviceTasks: ['문서 작성', '단순 편집'],
    expertType: '전문가',
    levelCriteria: {
      careerYears: '6년',
      education: '경영학 석사',
      field: 'IR/투자',
      overseasExperience: '해외 지사 근무 1년',
      domainExperience: 'IR 자료 번역 150건+',
    },
    rating: 4.7,
    completedCount: 180,
    profileImageUrl: 'https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 4,
    name: '최정밀',
    level: 'B',
    priority: 4,
    time: '평일 종일',
    serviceType: '기술 문서 번역',
    workUnit: '글자수',
    difficulty: '상',
    area: 'IT',
    subArea: '특허',
    serviceChannels: ['파일', '전화(화상)'],
    serviceTasks: ['문서 작성', '채점'],
    expertType: '고급전문가',
    levelCriteria: {
      careerYears: '7년',
      education: '공대 박사 수료',
      field: '반도체 장비',
      overseasExperience: '학회/프로젝트 5회 이상',
      domainExperience: '특허 명세서 번역 200건+',
    },
    rating: 4.85,
    completedCount: 240,
    profileImageUrl: 'https://images.pexels.com/photos/1181579/pexels-photo-1181579.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 5,
    name: '오세무',
    level: 'C',
    priority: 5,
    time: '언제든(긴급)',
    serviceType: '세무 보고서 번역',
    workUnit: '장당',
    difficulty: '상',
    area: '세무',
    subArea: '세무정산',
    serviceChannels: ['파일', '채팅'],
    serviceTasks: ['문서 작성', '단순 편집'],
    expertType: '전문가',
    levelCriteria: {
      careerYears: '5년',
      education: '회계학 전공',
      field: '법인세/부가세',
      overseasExperience: '없음',
      domainExperience: '세무 보고서 번역 120건+',
    },
    rating: 4.6,
    completedCount: 140,
    profileImageUrl: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 6,
    name: '정헬스',
    level: 'B',
    priority: 6,
    time: '평일 오후',
    serviceType: '의료 기록 번역',
    workUnit: '페이지',
    difficulty: '상',
    area: '의료',
    subArea: '임상기록',
    serviceChannels: ['파일'],
    serviceTasks: ['문서 작성', '단순 편집'],
    expertType: '전문가',
    levelCriteria: {
      careerYears: '6년',
      education: '의학 관련 석사',
      field: '임상 기록',
      overseasExperience: '해외 병원 연수 6개월',
      domainExperience: '의무기록 번역 180건+',
    },
    rating: 4.75,
    completedCount: 190,
    profileImageUrl: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 7,
    name: '한국제',
    level: 'A',
    priority: 7,
    time: '평일 오전',
    serviceType: '계약/법률 통역',
    workUnit: '시간당',
    difficulty: '상',
    area: '국제거래',
    subArea: '계약',
    serviceChannels: ['대면', '전화(화상)'],
    serviceTasks: ['문서 작성', '단순 편집'],
    expertType: '특수전문가',
    levelCriteria: {
      careerYears: '12년',
      education: '국제법 석사',
      field: '국제 계약',
      overseasExperience: '다국적 기업 근무 4년',
      domainExperience: '국제회의 통역/번역 400건+',
    },
    rating: 4.95,
    completedCount: 410,
    profileImageUrl: 'https://images.pexels.com/photos/1181715/pexels-photo-1181715.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 8,
    name: '서리서치',
    level: 'C',
    priority: 8,
    time: '주말',
    serviceType: '시장 조사 리포트 번역',
    workUnit: '페이지',
    difficulty: '중',
    area: '마케팅',
    subArea: '리서치',
    serviceChannels: ['파일'],
    serviceTasks: ['문서 작성', '설문'],
    expertType: '일반',
    levelCriteria: {
      careerYears: '3년',
      education: '마케팅 전공',
      field: '시장조사',
      overseasExperience: '없음',
      domainExperience: '리포트 번역 60건+',
    },
    rating: 4.4,
    completedCount: 70,
    profileImageUrl: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 9,
    name: '류컨설트',
    level: 'D',
    priority: 9,
    time: '평일 종일',
    serviceType: '자기소개서/이력서 번역',
    workUnit: '건당',
    difficulty: '하',
    area: '취업',
    subArea: '해외취업',
    serviceChannels: ['파일', '채팅'],
    serviceTasks: ['문서 작성'],
    expertType: '일반',
    levelCriteria: {
      careerYears: '2년',
      education: '영문학 전공',
      field: '취업/커리어',
      overseasExperience: '워킹홀리데이 1년',
      domainExperience: '이력서/자소서 번역 80건+',
    },
    rating: 4.3,
    completedCount: 90,
    profileImageUrl: 'https://images.pexels.com/photos/1181524/pexels-photo-1181524.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 10,
    name: '문세심',
    level: 'B',
    priority: 10,
    time: '언제든(긴급)',
    serviceType: '논문 번역 및 교정',
    workUnit: '장당',
    difficulty: '상',
    area: '학술',
    subArea: '논문',
    serviceChannels: ['파일'],
    serviceTasks: ['문서 작성', '단순 편집', '채점'],
    expertType: '고급전문가',
    levelCriteria: {
      careerYears: '9년',
      education: '영어영문학 박사',
      field: '학술 논문',
      overseasExperience: '해외 대학 박사 과정 4년',
      domainExperience: 'SCI 논문 번역/교정 250편+',
    },
    rating: 4.9,
    completedCount: 260,
    profileImageUrl: 'https://images.pexels.com/photos/1181515/pexels-photo-1181515.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];
